# Generated by Django 2.1 on 2018-11-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_group_subect_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='subect_name',
            new_name='subject_name',
        ),
    ]
