# Generated by Django 2.1 on 2018-11-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20181129_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='group',
            name='subject_name',
            field=models.ManyToManyField(blank=True, null=True, to='group.Subject'),
        ),
    ]
