# Generated by Django 2.1 on 2018-12-02 14:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_to', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateTimeField(default=datetime.datetime(2018, 12, 2, 14, 30, 45, 96615))),
                ('type', models.CharField(choices=[('C', 'Commision'), ('k', 'Kitchen Expenses'), ('STAT', 'Stationary'), ('A', 'Advertisement'), ('R', 'Rent'), ('EW', 'Electricity and Water'), ('PI', 'Phone and Internet'), ('M', 'Miscellnous')], default='M', max_length=50)),
                ('by_cheque', models.BooleanField(default=False)),
                ('cheque_no', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('courses', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('group', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('payto_id', models.CharField(blank=True, default='none', max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paid_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.IntegerField(null=True)),
                ('fee_submitted', models.IntegerField(default=0)),
                ('photo', models.FileField(blank=True, upload_to='bea')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3)),
                ('joined_date', models.DateField(default=datetime.datetime(2018, 12, 2, 14, 30, 45, 94525))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Shift')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.IntegerField(null=True)),
                ('photo', models.FileField(blank=True, upload_to='bea')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Shift')),
            ],
        ),
    ]
