# Generated by Django 2.1 on 2018-12-07 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181205_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fee_submitted',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='shift',
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='person_id',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='person_type',
            field=models.CharField(default='STU', max_length=10),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 16, 39, 52, 494849)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 7, 16, 39, 52, 492477)),
        ),
    ]
