# Generated by Django 2.1 on 2018-11-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, upload_to='bea'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.FileField(blank=True, upload_to='bea'),
        ),
    ]
