# Generated by Django 2.1 on 2018-12-08 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20181207_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='marks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 7, 16, 44, 303340)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 8, 7, 16, 44, 301188)),
        ),
    ]
