# Generated by Django 2.1 on 2018-11-27 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20181127_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 7, 35, 53, 435940)),
        ),
    ]
