# Generated by Django 2.1 on 2018-12-29 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181209_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 16, 55, 46, 338582)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 16, 55, 46, 336984)),
        ),
    ]
