# Generated by Django 2.1 on 2018-11-27 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181127_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 8, 7, 55, 905225)),
        ),
    ]
