# Generated by Django 2.1 on 2018-12-29 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20181229_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=2)),
                ('test_type', models.CharField(default='D', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupcourse',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 17, 43, 44, 849791)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 17, 43, 44, 847667)),
        ),
        migrations.AddField(
            model_name='marks',
            name='course_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.GroupCourse'),
        ),
    ]
