# Generated by Django 2.1 on 2018-11-27 12:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_auto_20181127_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_to', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('paid_date', models.DateTimeField(default=datetime.datetime(2018, 11, 27, 12, 32, 50, 6038))),
                ('type', models.CharField(choices=[('T', 'Teacher'), ('S', 'Student'), ('O', 'other')], default='O', max_length=50)),
                ('by_cheque', models.BooleanField(default=False)),
                ('cheque_no', models.DecimalField(blank=True, decimal_places=0, max_digits=5)),
                ('courses', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('group', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paid_date'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 12, 32, 50, 4506)),
        ),
    ]
