# Generated by Django 2.1 on 2018-12-29 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20181229_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='person_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 18, 4, 54, 23975)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 18, 4, 54, 21399)),
        ),
    ]
