# Generated by Django 2.1 on 2018-12-29 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20181229_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcourse',
            name='person_surname',
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 18, 7, 11, 760393)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 18, 7, 11, 757191)),
        ),
    ]
