# Generated by Django 2.1 on 2018-11-27 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20181127_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pay',
            name='cheque_no',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 13, 31, 26, 11721)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='type',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student'), ('O', 'Other')], default='O', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 13, 31, 26, 9820)),
        ),
    ]
