# Generated by Django 2.1 on 2018-11-27 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20181127_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='cheque_no',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 13, 36, 25, 771036)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 13, 36, 25, 769346)),
        ),
    ]
