# Generated by Django 2.1 on 2019-01-06 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20181229_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pay',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pay',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 8, 13, 5, 849242)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 6, 8, 13, 5, 846708)),
        ),
    ]
