# Generated by Django 2.1 on 2018-11-28 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20181127_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 12, 38, 4, 153394)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='type',
            field=models.CharField(choices=[('C', 'Commision'), ('k', 'Kitchen Expenses'), ('Stationary', 'STAT'), ('Advertisement', 'A'), ('Rent', 'R'), ('Electricity and Water', 'EW'), ('Phone and Internet', 'PI'), ('M', 'Miscellnous')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 28, 12, 38, 4, 151789)),
        ),
    ]
