# Generated by Django 2.1 on 2018-11-29 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20181128_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 10, 8, 52, 13679)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='type',
            field=models.CharField(choices=[('C', 'Commision'), ('k', 'Kitchen Expenses'), ('STAT', 'Stationary'), ('A', 'Advertisement'), ('R', 'Rent'), ('EW', 'Electricity and Water'), ('Phone and Internet', 'PI'), ('Miscellnous', 'M')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 29, 10, 8, 52, 12207)),
        ),
    ]
