# Generated by Django 2.1 on 2018-11-29 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20181129_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 10, 13, 35, 547504)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 29, 10, 13, 35, 545917)),
        ),
    ]
