# Generated by Django 2.1 on 2019-01-07 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20190107_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenquiry',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='studentenquiry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 7, 10, 26, 38, 791887, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='intrested_join_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 7, 10, 26, 38, 791860)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 10, 26, 38, 793919)),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 7, 10, 26, 38, 791196)),
        ),
    ]
