# Generated by Django 2.1 on 2018-11-30 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20181129_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 2, 19, 54, 566751)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='type',
            field=models.CharField(choices=[('C', 'Commision'), ('k', 'Kitchen Expenses'), ('STAT', 'Stationary'), ('A', 'Advertisement'), ('R', 'Rent'), ('EW', 'Electricity and Water'), ('PI', 'Phone and Internet'), ('M', 'Miscellnous')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 30, 2, 19, 54, 565173)),
        ),
    ]
